### ISSUE TITLE
Add open source license for onnxinfo

### ISSUE THREAD

**Issue by yungyuc** [ExplorerRay/onnxinfo#1]
@ExplorerRay , please add an open source license for your project.  If you are not sure how to do it, see https://github.com/solvcon/modmesh.

**Comment by ExplorerRay** [comment]
https://github.com/ExplorerRay/onnxinfo/pull/2

Do you have any suggestions about this pull request? If no, I will merge and then close this issue.

**Comment by yungyuc** [comment]
It's ok as long as it's an open source license.
